spring.application.name=employeemanagement
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management?useSSL=false&serverTimezone=UTC
spring.datasource.username=roger
spring.datasource.password=bandana

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=mappings

# Configurações do JWT (A chave deve ter pelo menos 256 bits / 32 caracteres)
jwt.secret=your_secret_key_here_change_it_must_be_long_enough_32chars_min
jwt.expiration-time=3600000